def print_intro():
    print("          .=     ,        =.")
    print("  _  _   /'/    )\,/,/(_   \ \ ")
    print("   `//-.|  (  ,\\)\//\)\/_  ) |")
    print("   //___\   `\\\/\\/\/\\///'  /")
    print(",-'~`-._ `'--'_   `'''`  _ \`''~-,_")
    print("\       `-.  '_`.      .'_` \ ,-'~`/")
    print(" `.__.-'`/   (-\        /-) |-.__,'")
    print("   ||   |     \O)  /^\ (O/  |")
    print("   `\\  |         /   `\    /")
    print("     \\  \       /      `\ /")
    print("      `\\ `-.  /' .---.--.\ ")
    print("        `\\/`~(, '()      ('")
    print("         /(O) \\   _,.-.,_)")
    print("        //  \\ `\'`      /")
    print("       / |  ||   `''''~'`")
    print("     /'  |__||")
    print("           `o")
    print("\nWelcome to Bulls and Cows\n")
    return

print_intro()